spring.application.name=demo
server.port=8081

# H2 Database Configuration (File-based)
spring.datasource.url=jdbc:h2:file:./data/attendance_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=



# Set JPA properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console enabled at /h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console